CREATE TABLE jan_2023_jobs AS
SELECT *
FROM job_postings_fact
WHERE EXTRACT (MONTH FROM JOB_POSTED_DATE) = 1
AND EXTRACT (YEAR FROM JOB_POSTED_DATE) = 2023;

CREATE TABLE FEB_2023_jobs AS
SELECT *
FROM job_postings_fact
WHERE EXTRACT (MONTH FROM JOB_POSTED_DATE) = 2
AND EXTRACT (YEAR FROM JOB_POSTED_DATE) = 2023;

CREATE TABLE MAR_2023_jobs AS
SELECT *
FROM job_postings_fact
WHERE EXTRACT (MONTH FROM JOB_POSTED_DATE) = 3
AND EXTRACT (YEAR FROM JOB_POSTED_DATE) = 2023;

SELECT *
FROM jan_2023_jobs;